# Generated by Django 4.2 on 2023-04-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctoremail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patientemail',
            field=models.TextField(),
        ),
    ]
